### ISSUE TITLE
Issue with growth rate calculation

### ISSUE THREAD

**Issue by cheekolegend** [Ati-74/Trackrefiner#1]
I cannot run the code on one of my data sets; the code crashes due to an error in the growth rate calculation. 

(imageprocessing) C:\Users\aaron\CellProfilerAnalysis>python RunDataProcessing.py
interval time: 0.05
1 pixel is equal to: 0.144
growth rate methodLinear Regression
input file: C:/Users/aaron/CellProfilerAnalysis/unit test/real_images/scene5/scene5.csv
output directory: C:/Users/aaron/CellProfilerAnalysis/unit test/real_images/scene5
C:\Users\aaron\CellProfilerAnalysis\CellProfilerAnalysis\strain\correction\action\CalcGrowthRate.py:15: RuntimeWarning: invalid value encountered in log
  linear_regressor.fit(np.array(time).reshape(-1, 1), np.log(np.array(length).reshape(-1, 1)))
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "RunDataProcessing.py", line 17, in start_processing
    process_data(input_file, output_directory_path_as_input_folder, interval_time=float(interval_time.get()),
  File "C:\Users\aaron\CellProfilerAnalysis\CellProfilerAnalysis\strain\ProcessCellProfilerData.py", line 28, in process_data
    processed_df = bacteria_analysis_func(data_frame, interval_time, growth_rate_method)
  File "C:\Users\aaron\CellProfilerAnalysis\CellProfilerAnalysis\strain\ExperimentalDataProcessing.py", line 34, in bacteria_analysis_func
    elongation_rate = calculate_growth_rate(bacterium_life_history, interval_time, growth_rate_method)
  File "C:\Users\aaron\CellProfilerAnalysis\CellProfilerAnalysis\strain\correction\action\CalcGrowthRate.py", line 39, in calculate_growth_rate
    elongation_rate = calculate_linear_regression_growth_rate(time, length)
  File "C:\Users\aaron\CellProfilerAnalysis\CellProfilerAnalysis\strain\correction\action\CalcGrowthRate.py", line 15, in calculate_linear_regression_growth_rate
    linear_regressor.fit(np.array(time).reshape(-1, 1), np.log(np.array(length).reshape(-1, 1)))
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\linear_model\_base.py", line 662, in fit
    X, y = self._validate_data(
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\utils\validation.py", line 979, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\utils\validation.py", line 989, in _check_y
    y = check_array(
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\utils\validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "C:\Users\aaron\anaconda3\envs\imageprocessing\lib\site-packages\sklearn\utils\validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by Ati-74** [comment]
This issue has been resolved thanks
